var heading = "MY first console project";
console.log(heading);
var first_name = "Ranbir";
var last_name = "Kapoor";
var full_name = first_name.concat(last_name);
console.log(full_name);
var a = 10;
var b = 5;
var add =a+b;
console.log(add);
console.log(b);
var d = 50;
console.log(d);
var c ="2";
console.log(c);